# Generated by Django 4.1.4 on 2022-12-18 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_reputacija_korisnik_points'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reputacija',
            name='points',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
