# Generated by Django 4.1.4 on 2022-12-18 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_reputacija_points'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reputacija',
            name='points',
            field=models.IntegerField(blank=True, null=True, verbose_name='Reputacija'),
        ),
    ]
