# Generated by Django 4.1.4 on 2022-12-18 15:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_reputacija_points'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='korisnik',
            name='points',
        ),
        migrations.AddField(
            model_name='reputacija',
            name='user_name',
            field=models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.korisnik'),
        ),
    ]
