# Generated by Django 4.1.4 on 2022-12-18 16:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_komentar_blog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='komentar',
            name='user_name',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.korisnik'),
        ),
    ]
