# Generated by Django 4.1.4 on 2022-12-18 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_komentar_user_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='komentar',
            name='theme',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='Tema bloga'),
        ),
    ]
