# Generated by Django 4.1.4 on 2022-12-18 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_komentar_theme'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='komentar',
            name='theme',
        ),
        migrations.AddField(
            model_name='blog',
            name='theme',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='Tema bloga'),
        ),
    ]
