# Generated by Django 4.1.4 on 2022-12-18 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_remove_komentar_theme_blog_theme'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='theme',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Tema bloga'),
        ),
    ]
